export interface TypeAData {
  Month: string;
  "Cab No": string;
  "S. No.": string;
  "Vehicle Type": string;
  "Fix/Trip": string;
  "Route Name": string;
  "Ertiga/Dzire/Tempo": string;
  "Fix Price": number;
  "Trip Amount": number;
  "HR TAX": number;
  "MCD / Other Paid": number;
  "Total Trip": number;
  Amount: number;
  "Add Taxi Duty Amount": number;
  "Gross Total": number;
  "1% TDS": number;
  "Total Amount": number;
  "EMI Amount": number;
  "EMI Number": number;
  Insurance: number;
  Cash: number;
  "A/C Pay": number;
  "A/C Card": number;
  "Petrol/CNG": number;
  Maintenance: number;
  Compliance: number;
  "ESI/PF": number;
  Salary: number;
  Driver: number;
  "HR Tax/Taxi Others": number;
  "GPS Charge": number;
  "Down Payment": number;
  "Total Expenses": number;
  "Net Total": number;
  "Previous Minus": number;
  "Final Amount": number;
  "Owner Name": string;
}
