export interface TypeBData {
  Month: string;
  "Cab No": string;
  "Cab Type": string;
  "Vehicle Type": string;
  "Driver Name": string;
  "Owner Name"?: string;
  "Old Amex Trips": number;
  "74-A Amex Trips": number;
  "Total Trips": number;
  "DLI(FRONT)": number;
  "DLI(B2B)": number;
  "FBD(FRONT)": number;
  "FBD(B2B)": number;
  "GGN(FRONT)": number;
  "GGN(B2B)": number;
  "NOIDA(FRONT)": number;
  "NOIDA(B2B)": number;
  "GZB(FRONT)": number;
  "GZB(B2B)": number;
  "Installment": number;
  "No. of Installments": number;
  "Petrol/CNG": number;
  "Penalty": number;
  "Insurance": number;
  "Cash": number;
  "A/C Pay": number;
  "CNG Card": number;
  "Down Payment": number;
  "ESI/PF": number;
  "Driver Salary": number;
  "Maintenance": number;
  "Compliance": number;
  "GPS Rent": number;
  "HR Tax": number;
  "MCD + Fast Tag + UP Tax (Recovery)": number;
  "Total Expenses": number;
  "Gross Amount": number;
  "Previous Minus/Plus": number;
  "Final Amount": number;
  "Old Amex Amount": number;
  "74-A Company Amount": number;
  "Shuttle Cab Amount": number;
  "Guard Trips": number;
  "Guard Amount": number;
  "Cyber Guard Trips"?: number;
  "Cyber Guard Amount"?: number;

  "G_T"?: number;
  "GTM"?: number;

  "CyberCity_Sum_Trip"?: number;
  "CyberCity_Sum_Amt"?: number;
  "Amex Amount": number;
  "Fastag Amount": number;
  "Jaquar Payment": number;
  "Hartron": number;
  "Total Amount (Before TDS)": number;
  "TDS @1%": number;
  "Total Amount (After TDS)": number;
  "Account Name": string;
  "Account Number": string;
  "IFSC Code": string;
  "PAN Name": string;
  "PAN Number": string;
  "Father Name": string;
  // Campus Trips detailed breakdown (usually mapped from specific columns)
  "DLI_FRONT_AMT"?: number;
  "DLI_B2B_AMT"?: number;
  "FBD_FRONT_AMT"?: number;
  "FBD_B2B_AMT"?: number;
  "GGN_FRONT_AMT"?: number;
  "GGN_B2B_AMT"?: number;
  "NOIDA_FRONT_AMT"?: number;
  "NOIDA_B2B_AMT"?: number;
  "GZB_FRONT_AMT"?: number;
  "GZB_B2B_AMT"?: number;
  "C_EXTRA_GGN_TRIP"?: number;
  "C_EXTRA_GGN_AMT"?: number;
  "C_EXTRA_DLI_FBD_GZB_TRIP"?: number;
  "C_EXTRA_DLI_FBD_GZB_AMT"?: number;
  "C_GUARD_TRIP"?: number;
  "C_GUARD_AMT"?: number;
  "Per_Trip_Extra_GGN_AMT"?: number;
  "Extra_DLI_FBD_GZB_AMT"?: number;
}
